[package]
name = "suiproof"
version = "0.0.1"
edition = "2024.beta"

[addresses]
suiproof = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "main" }
